

CREATE DATABASE SUMINISTRO;
USE SUMINISTRO;


-- PROVEEDOR
CREATE TABLE PROVEEDOR (
    NIF INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(100)
);

-- CLIENTE
CREATE TABLE CLIENTE (
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    FECHA_NAC DATE,
    TFNO INT
);

-- TABLA COMPRA 
CREATE TABLE COMPRA (
    DNI_CLIENTE CHAR(9),
    CODIGO_PRODUCTO INT,
    CONSTRAINT COM_PK PRIMARY KEY (DNI_CLIENTE, CODIGO_PRODUCTO)
);

-- AÑADIR LAS FK DE COMPRA
ALTER TABLE COMPRA
ADD CONSTRAINT CLI_FK
FOREIGN KEY (DNI_CLIENTE)
REFERENCES CLIENTE(DNI)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE COMPRA
ADD CONSTRAINT PRO_FK
FOREIGN KEY (CODIGO_PRODUCTO)
REFERENCES PRODUCTO(CODIGO)
ON UPDATE CASCADE
ON DELETE CASCADE;

-- PRODUCTO 
CREATE TABLE PRODUCTO (
    CODIGO INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    PRECIO DOUBLE
);


