-- BASE DE DATOS DDL1 (EJERCICIO1)
-- MODULO DE BASES DE DATOS 
-- CURSO 25-26
-- DANIEL IGLESIAS

CREATE DATABASE DDL1;

USE DDL1;

CREATE TABLE CLIENTE(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(25),
PIMER_APELLIDO VARCHAR(15) NOT NULL,
CIUDAD VARCHAR(100),
CATEGORIA INT 
);

CREATE TABLE COMERCIAL(
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO1 VARCHAR(100) NOT NULL,
APELLIDO2 VARCHAR(100),
CIUDAD VARCHAR(100),
COMINSION FLOAT
);

SHOW TABLES;
