-- Crear la base de datos y usarla
CREATE DATABASE DDL_3;
USE DDL_3;

-- Tabla EMPLEADOS
CREATE TABLE EMPLEADOS(
    NUM_EMP INT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    EDAD INT,
    TITULACION VARCHAR(50),
    FECHA_CONTRATO DATE,
    DIRECTOR INT,
    OFICINA INT,
    VENTAS FLOAT
);

-- Relaciones de EMPLEADOS DIRECTOR
ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_DIRECTOR
FOREIGN KEY (DIRECTOR) REFERENCES EMPLEADOS(NUM_EMP);

-- OFICINA
-- Tabla OFICINAS
CREATE TABLE OFICINAS(
    OFICINA INT PRIMARY KEY,
    CIUDAD VARCHAR(30),
    REGION VARCHAR(40),
    OBJETIVO FLOAT,
    VENTAS FLOAT
);

-- Ahora sí añadimos la FK de OFICINA
ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_OFICINAS
FOREIGN KEY (OFICINA) REFERENCES OFICINAS(OFICINA);

-- Tabla PRODUCTOS
CREATE TABLE PRODUCTOS(
    ID_PRODUCTO INT,
    ID_FAB CHAR(10),
    DESCRIPCION VARCHAR(30) NOT NULL,
    EXISTENCIAS INT,
    PRIMARY KEY(ID_PRODUCTO, ID_FAB)
);

-- Ver estructura de PRODUCTOS
DESC PRODUCTOS;

-- Tabla CLIENTES
CREATE TABLE CLIENTES(
    ID_CLIENTE INT PRIMARY KEY,
    NOM_CLIENTE CHAR(10),
    LIMITE_CREDITO DECIMAL(10,2)  -- Se añade directamente
);

-- Tabla PEDIDOS
CREATE TABLE PEDIDOS(
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_PEDIDO DATETIME NOT NULL,
    CLI INT NOT NULL,
    EMP INT NOT NULL,
    FAB INT NOT NULL,
    PROD INT NOT NULL, 
    CANTIDAD INT NOT NULL,
    IMPORTE FLOAT NOT NULL
);

-- Ver estructura de PEDIDOS
DESC PEDIDOS;

-- Relaciones de PEDIDOS
ALTER TABLE PEDIDOS
ADD CONSTRAINT PRODUCTOS_FK
FOREIGN KEY (PROD) REFERENCES PRODUCTOS(ID_PRODUCTO)
 ON DELETE CASCADE  ON UPDATE CASCADE;

ALTER TABLE PEDIDOS
ADD CONSTRAINT  CLIENTE_FK
FOREIGN KEY (CLI) REFERENCES CLIENTES(ID_CLIENTE) 
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PEDIDOS
ADD CONSTRAINT EMPLEADOS_FK
FOREIGN KEY (EMP) REFERENCES EMPLEADOS(NUM_EMP)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PEDIDOS
ADD CONSTRAINT FABRICANTE_FK foreign key(FAB)
references FABRICANTE(ID_FABRICANTE)   
ON DELETE CASCADE ON UPDATE CASCADE;
-- Tabla FABRICANTE
CREATE TABLE FABRICANTE(
    ID_FABRICANTE INT PRIMARY KEY,
    NOM_FABRICANTE CHAR(10)
);


